# Generated by Django 5.2.6 on 2025-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdevision',
            name='id',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='id',
        ),
        migrations.AddField(
            model_name='academicdevision',
            name='academic_devision_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='academic_year_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='state',
            name='state_id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
