# Generated by Django 5.2.6 on 2025-10-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_remove_academicdevision_id_remove_academicyear_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-branch_id'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
