# Generated by Django 5.2.6 on 2025-10-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_section_alter_branch_options'),
        ('students', '0006_section_alter_student_section_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
