# Generated by Django 5.2.6 on 2025-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orientation',
            name='id',
        ),
        migrations.AddField(
            model_name='classname',
            name='class_name_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orientation',
            name='orientation_id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
