# Generated by Django 5.2.6 on 2025-10-02 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_remove_academicdevision_id_remove_academicyear_id_and_more'),
        ('students', '0002_remove_classname_id_remove_orientation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStatus',
            fields=[
                ('admission_status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admission_status', models.CharField(max_length=250, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('varna_gender_id', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('varna_student_id', models.CharField(blank=True, max_length=250, null=True)),
                ('SCS_Number', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_academic_year', to='branches.academicyear')),
                ('admission_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_admission_status', to='students.admissionstatus')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_branch', to='branches.branch')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_gender', to='students.gender')),
                ('orientation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_orientation', to='students.orientation')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_state', to='branches.state')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_class_name', to='students.classname')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_zone', to='branches.zone')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['SCS_Number'], name='student_scs_number_idx'), models.Index(fields=['is_active'], name='student_is_active_idx'), models.Index(fields=['branch'], name='student_branch_idx')],
            },
        ),
    ]
