# Generated by Django 5.2.6 on 2025-10-03 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_section_alter_branch_options'),
        ('students', '0003_admissionstatus_gender_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='class_name_id',
        ),
        migrations.RemoveField(
            model_name='orientation',
            name='orientation_id',
        ),
        migrations.AddField(
            model_name='classname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='orientation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_section', to='branches.section'),
        ),
    ]
