# Generated by Django 5.2.6 on 2025-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_classname_class_name_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orientation',
            name='id',
        ),
        migrations.AddField(
            model_name='classname',
            name='class_name_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orientation',
            name='orientation_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
