# Generated by Django 5.2.6 on 2025-10-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_section_alter_branch_options'),
        ('students', '0005_remove_classname_id_remove_orientation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('external_name', models.CharField(blank=True, max_length=250, null=True)),
                ('external_id', models.CharField(blank=True, max_length=250, null=True)),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('has_students', models.BooleanField(default=False)),
                ('number_of_students', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_academic_year', to='branches.academicyear')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_building', to='branches.branch')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_class_name', to='students.classname')),
                ('orientation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_orientation', to='students.orientation')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_section', to='students.section'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['building'], name='students_se_buildin_fea9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['class_name'], name='students_se_class_n_7aeeba_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['orientation'], name='students_se_orienta_fdf43e_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['academic_year'], name='students_se_academi_ac4847_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_active'], name='students_se_is_acti_4d540f_idx'),
        ),
    ]
