# Generated by Django 5.2.6 on 2025-10-06 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_section'),
        ('students', '0006_section_alter_student_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOrientations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_orientations_acyear', to='branches.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_orientations', to='branches.branch')),
                ('orientations', models.ManyToManyField(blank=True, related_name='branch_orientations', to='students.orientation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'branch'), name='unique_branch_ac_year')],
            },
        ),
    ]
