# Generated by Django 5.2.6 on 2025-10-06 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_section'),
        ('students', '0007_branchorientations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='section',
            name='students_se_buildin_fea9ea_idx',
        ),
        migrations.RemoveField(
            model_name='section',
            name='building',
        ),
        migrations.AddField(
            model_name='section',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_branch', to='branches.branch'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['branch'], name='students_se_branch__d24e90_idx'),
        ),
    ]
