# Generated by Django 5.2.6 on 2025-10-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_section_students_se_buildin_fea9ea_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='number_of_students',
        ),
    ]
