# Generated by Django 5.2.6 on 2025-10-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_section_number_of_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='external_id',
            new_name='varna_section_id',
        ),
    ]
