# Generated by Django 5.2.6 on 2025-10-02 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_remove_academicdevision_id_remove_academicyear_id_and_more'),
        ('students', '0002_remove_classname_id_remove_orientation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('short_code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('exam_type_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_subjects_marks', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=3, null=True)),
                ('overall_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('section_rank', models.IntegerField(blank=True, null=True)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('zone_rank', models.IntegerField(blank=True, null=True)),
                ('state_rank', models.IntegerField(blank=True, null=True)),
                ('all_india_rank', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_academic_year', to='branches.academicyear')),
                ('orientations', models.ManyToManyField(blank=True, related_name='exams_orientations', to='students.orientation')),
                ('student_classes', models.ManyToManyField(blank=True, related_name='exams_classes', to='students.classname')),
            ],
        ),
        migrations.CreateModel(
            name='ExamInstance',
            fields=[
                ('exam_instance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('has_internal_marks', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('exam_start_time', models.TimeField()),
                ('exam_end_time', models.TimeField()),
                ('maximum_marks_external', models.IntegerField(blank=True, null=True)),
                ('maximum_marks_internal', models.IntegerField(blank=True, null=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_instance_exam', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_marks', models.IntegerField(blank=True, null=True)),
                ('internal_marks', models.IntegerField(blank=True, null=True)),
                ('marks_obtained', models.IntegerField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('section_rank', models.IntegerField(blank=True, null=True)),
                ('zone_rank', models.IntegerField(blank=True, null=True)),
                ('state_rank', models.IntegerField(blank=True, null=True)),
                ('all_india_rank', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results_attendance', to='exams.examattendancestatus')),
                ('exam_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results_exam_instance', to='exams.examinstance')),
            ],
        ),
    ]
