# Generated by Django 5.2.6 on 2025-10-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_section'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsummary',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_exam_summary_academic_year', to='branches.academicyear'),
        ),
        migrations.AddField(
            model_name='studentexamsummary',
            name='is_progresscard',
            field=models.BooleanField(default=False),
        ),
    ]
