# Generated by Django 5.2.6 on 2025-10-02 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0003_admissionstatus_gender_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_exam_type', to='exams.examtype'),
        ),
        migrations.AddField(
            model_name='gradeboundary',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_bound_exam_type', to='exams.examtype'),
        ),
        migrations.AddField(
            model_name='gradeboundary',
            name='orientation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_bound_orientation', to='students.orientation'),
        ),
        migrations.AddField(
            model_name='studentexamsummary',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_summary_exam', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='studentexamsummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_summary_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_names',
            field=models.ManyToManyField(blank=True, related_name='subject_classes', to='students.classname'),
        ),
        migrations.AddField(
            model_name='examinstance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_instance_subject', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='subjectskill',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='exams.subject'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student'], name='exams_examr_student_dfce85_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam_instance'], name='exams_examr_exam_in_589974_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['marks_obtained'], name='exams_examr_marks_o_e75c44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'exam_instance')},
        ),
        migrations.AlterUniqueTogether(
            name='gradeboundary',
            unique_together={('exam_type', 'orientation', 'grade')},
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['student'], name='exams_stude_student_6e2995_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['exam'], name='exams_stude_exam_id_e9ad01_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['total_subjects_marks'], name='exams_stude_total_s_3e513a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentexamsummary',
            unique_together={('student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectskill',
            unique_together={('subject', 'name')},
        ),
    ]
