# Generated by Django 5.2.6 on 2025-10-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentexamsummary_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examskillresult',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
