# Generated by Django 5.2.6 on 2025-10-03 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_section_alter_branch_options'),
        ('exams', '0002_initial'),
        ('students', '0004_remove_classname_class_name_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSkillResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentexamsummary',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subjectskill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_devisions',
            field=models.ManyToManyField(blank=True, related_name='exam_academic_devisions', to='branches.academicdevision'),
        ),
        migrations.AddField(
            model_name='exam',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='exams_branches', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='exam',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='exams_states', to='branches.state'),
        ),
        migrations.AddField(
            model_name='exam',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='exams_zones', to='branches.zone'),
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_devisions',
            field=models.ManyToManyField(blank=True, related_name='subject_academic_devisions', to='branches.academicdevision'),
        ),
        migrations.AddField(
            model_name='subject',
            name='display_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examattendancestatus',
            name='short_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentexamsummary',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('name', 'academic_year', 'exam_type'), name='unique_exam_per_year_type'),
        ),
        migrations.AddConstraint(
            model_name='examinstance',
            constraint=models.UniqueConstraint(fields=('exam', 'subject'), name='unique_exam_subject_instance'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('student', 'exam_instance'), name='unique_student_exam_instance'),
        ),
        migrations.AddConstraint(
            model_name='studentexamsummary',
            constraint=models.UniqueConstraint(fields=('student', 'exam'), name='unique_student_exam_summary'),
        ),
        migrations.AddConstraint(
            model_name='subjectskill',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='unique_subject_skill_name'),
        ),
        migrations.AddField(
            model_name='examskillresult',
            name='exam_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_results', to='exams.examresult'),
        ),
        migrations.AddField(
            model_name='examskillresult',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_results', to='exams.subjectskill'),
        ),
        migrations.AddConstraint(
            model_name='examskillresult',
            constraint=models.UniqueConstraint(fields=('exam_result', 'skill'), name='unique_examresult_skill'),
        ),
    ]
