# Generated by Django 5.2.6 on 2025-10-28 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_section'),
        ('exams', '0003_examskillresult_percentage'),
        ('students', '0010_rename_external_id_section_varna_section_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Exam Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Subject Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='exam',
            name='unique_exam_per_year_type',
        ),
        migrations.AlterField(
            model_name='coscholasticgrade',
            name='name',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='gradeboundary',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='coscholasticgrade',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_scholastic_grade_category', to='exams.examcategory'),
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams_category', to='exams.examcategory'),
        ),
        migrations.AddField(
            model_name='gradeboundary',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_boundary_category', to='exams.examcategory'),
        ),
        migrations.AddIndex(
            model_name='coscholasticgrade',
            index=models.Index(fields=['category'], name='exams_cosch_categor_edc459_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['category'], name='exams_exam_categor_1e6004_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeboundary',
            index=models.Index(fields=['category'], name='exams_grade_categor_901a81_idx'),
        ),
        migrations.AddConstraint(
            model_name='coscholasticgrade',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_co_scholastic_grade_category'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('name', 'academic_year', 'exam_type', 'category'), name='unique_exam_per_year_type_category'),
        ),
        migrations.AddConstraint(
            model_name='gradeboundary',
            constraint=models.UniqueConstraint(fields=('category', 'grade'), name='unique_grade_boundary_category'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='exams.subjectcategory'),
        ),
    ]
