# Generated by Django 5.2.6 on 2025-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examskillresult_alter_examresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinstance',
            name='cut_off_marks_external',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinstance',
            name='cut_off_marks_internal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examinstance',
            name='has_external_marks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examinstance',
            name='has_subject_skills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examinstance',
            name='subject_skills',
            field=models.ManyToManyField(blank=True, related_name='exam_instances', to='exams.subjectskill'),
        ),
    ]
