# Generated by Django 5.2.6 on 2025-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examinstance_cut_off_marks_external_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattendancestatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='examskillresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gradeboundary',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentexamsummary',
            name='id',
        ),
        migrations.AddField(
            model_name='examattendancestatus',
            name='exam_attendance_status_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_result_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='examskillresult',
            name='examp_skill_result_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gradeboundary',
            name='grade_boundary_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studentexamsummary',
            name='students_exam_summary_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
