# Generated by Django 5.2.6 on 2025-10-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examcategory_subjectcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
