# Generated by Django 5.2.6 on 2025-10-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='sequence',
        ),
        migrations.AddField(
            model_name='examinstance',
            name='sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
