# Generated by Django 5.2.6 on 2025-10-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_section_alter_branch_options'),
        ('exams', '0005_remove_examattendancestatus_id_remove_examresult_id_and_more'),
        ('students', '0004_remove_classname_class_name_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGrade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('point', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-point'],
            },
        ),
        migrations.RemoveField(
            model_name='examskillresult',
            name='value',
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year'], name='exams_exam_academi_f5cdc5_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type'], name='exams_exam_exam_ty_ccbba1_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year', 'exam_type'], name='exams_exam_academi_b14863_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_visible'], name='exams_exam_is_visi_8f05f8_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_active'], name='exams_exam_is_acti_1c1d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_date', 'end_date'], name='exams_exam_start_d_3b125a_idx'),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['exam'], name='exams_exami_exam_id_1eafcd_idx'),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['subject'], name='exams_exami_subject_97193c_idx'),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['date'], name='exams_exami_date_a400ff_idx'),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['is_active'], name='exams_exami_is_acti_5801d7_idx'),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['has_external_marks'], name='exams_exami_has_ext_1a7bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['has_internal_marks'], name='exams_exami_has_int_4fc43e_idx'),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['has_subject_skills'], name='exams_exami_has_sub_85c11f_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam_instance', 'marks_obtained'], name='exams_examr_exam_in_7ee976_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['percentage'], name='exams_examr_percent_e615f8_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['class_rank'], name='exams_examr_class_r_c34608_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['section_rank'], name='exams_examr_section_b5f189_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['zone_rank'], name='exams_examr_zone_ra_2b7349_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['state_rank'], name='exams_examr_state_r_fb1c37_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['all_india_rank'], name='exams_examr_all_ind_81849d_idx'),
        ),
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['is_active'], name='exams_examt_is_acti_89e782_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['percentage'], name='exams_stude_percent_4b116d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['class_rank'], name='exams_stude_class_r_9c264f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['section_rank'], name='exams_stude_section_bae9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['zone_rank'], name='exams_stude_zone_ra_aa2b89_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['state_rank'], name='exams_stude_state_r_02c7be_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['all_india_rank'], name='exams_stude_all_ind_1ab601_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['is_active'], name='exams_stude_is_acti_6939d8_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='exams_subje_is_acti_d4c6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectskill',
            index=models.Index(fields=['subject'], name='exams_subje_subject_f702c1_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectskill',
            index=models.Index(fields=['is_active'], name='exams_subje_is_acti_3046f6_idx'),
        ),
        migrations.AddIndex(
            model_name='skillgrade',
            index=models.Index(fields=['name'], name='exams_skill_name_a22cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='skillgrade',
            index=models.Index(fields=['point'], name='exams_skill_point_f07eeb_idx'),
        ),
        migrations.AddField(
            model_name='examskillresult',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_skill_results', to='exams.skillgrade'),
        ),
        migrations.AddIndex(
            model_name='examskillresult',
            index=models.Index(fields=['exam_result'], name='exams_exams_exam_re_fd9b34_idx'),
        ),
        migrations.AddIndex(
            model_name='examskillresult',
            index=models.Index(fields=['skill'], name='exams_exams_skill_i_b9b403_idx'),
        ),
        migrations.AddIndex(
            model_name='examskillresult',
            index=models.Index(fields=['grade'], name='exams_exams_grade_i_bfbe4d_idx'),
        ),
    ]
