# Generated by Django 5.2.6 on 2025-10-06 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_skillgrade_remove_examskillresult_value_and_more'),
        ('students', '0007_branchorientations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubjectSkillInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_external_marks', models.BooleanField(default=False)),
                ('has_internal_marks', models.BooleanField(default=False)),
                ('has_subject_co_scholastic_grade', models.BooleanField(default=True)),
                ('maximum_marks_external', models.IntegerField(blank=True, null=True)),
                ('cut_off_marks_external', models.IntegerField(blank=True, null=True)),
                ('maximum_marks_internal', models.IntegerField(blank=True, null=True)),
                ('cut_off_marks_internal', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SkillGrade',
            new_name='CoScholasticGrade',
        ),
        migrations.RemoveIndex(
            model_name='examresult',
            name='exams_examr_marks_o_e75c44_idx',
        ),
        migrations.RemoveIndex(
            model_name='examresult',
            name='exams_examr_exam_in_7ee976_idx',
        ),
        migrations.RemoveIndex(
            model_name='examskillresult',
            name='exams_exams_grade_i_bfbe4d_idx',
        ),
        migrations.RenameField(
            model_name='examresult',
            old_name='marks_obtained',
            new_name='skill_external_marks',
        ),
        migrations.RenameField(
            model_name='examskillresult',
            old_name='grade',
            new_name='co_scholastic_grade',
        ),
        migrations.RenameIndex(
            model_name='coscholasticgrade',
            new_name='exams_cosch_name_0457e1_idx',
            old_name='exams_skill_name_a22cb2_idx',
        ),
        migrations.RenameIndex(
            model_name='coscholasticgrade',
            new_name='exams_cosch_point_b87080_idx',
            old_name='exams_skill_point_f07eeb_idx',
        ),
        migrations.AddField(
            model_name='examinstance',
            name='has_subject_co_scholastic_grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examresult',
            name='co_scholastic_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_result_co_scholastic_grade', to='exams.coscholasticgrade'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='skill_internal_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='skill_total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examskillresult',
            name='external_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examskillresult',
            name='internal_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examskillresult',
            name='marks_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['has_subject_co_scholastic_grade'], name='exams_exami_has_sub_eba27b_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['external_marks'], name='exams_examr_externa_8a2748_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['total_marks'], name='exams_examr_total_m_8f698b_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam_instance', 'external_marks'], name='exams_examr_exam_in_64d248_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam_instance', 'total_marks'], name='exams_examr_exam_in_017f73_idx'),
        ),
        migrations.AddIndex(
            model_name='examskillresult',
            index=models.Index(fields=['co_scholastic_grade'], name='exams_exams_co_scho_c41e6c_idx'),
        ),
        migrations.AddField(
            model_name='examsubjectskillinstance',
            name='exam_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_skills_instance_exam_instance', to='exams.examinstance'),
        ),
        migrations.AddField(
            model_name='examsubjectskillinstance',
            name='subject_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_skill_instance_subject_skill', to='exams.subjectskill'),
        ),
        migrations.AddIndex(
            model_name='examsubjectskillinstance',
            index=models.Index(fields=['exam_instance'], name='exams_exams_exam_in_dfea8a_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubjectskillinstance',
            index=models.Index(fields=['subject_skill'], name='exams_exams_subject_d85869_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubjectskillinstance',
            index=models.Index(fields=['is_active'], name='exams_exams_is_acti_4528bb_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubjectskillinstance',
            index=models.Index(fields=['has_external_marks'], name='exams_exams_has_ext_1644be_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubjectskillinstance',
            index=models.Index(fields=['has_internal_marks'], name='exams_exams_has_int_dd11b7_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubjectskillinstance',
            index=models.Index(fields=['has_subject_co_scholastic_grade'], name='exams_exams_has_sub_a7b27d_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsubjectskillinstance',
            constraint=models.UniqueConstraint(fields=('exam_instance', 'subject_skill'), name='unique_exam_subject_skill_instance'),
        ),
    ]
