# Generated by Django 5.2.6 on 2025-10-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_exam_sequence_examinstance_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinstance',
            name='subject_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_instance_subject_category', to='exams.subjectcategory'),
        ),
    ]
