# Generated by Django 5.2.6 on 2025-11-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_section'),
        ('exams', '0007_examinstance_subject_category'),
        ('students', '0010_rename_external_id_section_varna_section_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentexamsummary',
            index=models.Index(fields=['academic_year'], name='exams_stude_academi_28797c_idx'),
        ),
    ]
