# Generated by Django 5.2.6 on 2025-10-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_section'),
        ('exams', '0007_examsubjectskillinstance_and_more'),
        ('students', '0009_remove_section_number_of_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_progress_card_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_progress_card_visible'], name='exams_exam_is_prog_0e2dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['exam', 'subject', 'is_active'], name='exams_exami_exam_id_88fc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam_instance', 'student'], name='idx_examresult_exam_student'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam_instance', 'is_active'], name='idx_examresult_exam_active'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'is_active'], name='idx_examresult_student_active'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam_instance', 'percentage'], name='idx_examresult_exam_percentage'),
        ),
        migrations.AddIndex(
            model_name='examskillresult',
            index=models.Index(fields=['exam_result', 'skill', 'co_scholastic_grade'], name='exams_exams_exam_re_051e48_idx'),
        ),
    ]
