# Generated by Django 5.2.6 on 2025-10-07 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_section'),
        ('exams', '0009_coscholasticgrade_created_at_and_more'),
        ('students', '0009_remove_section_number_of_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='marks_entry_expiry_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BranchWiseExamResultStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('is_progress_card_downloaded', models.BooleanField(default=False)),
                ('marks_completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('marks_entry_expiry_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_sections', models.PositiveIntegerField(default=0)),
                ('number_of_sections_completed', models.PositiveIntegerField(default=0)),
                ('number_of_sections_pending', models.PositiveIntegerField(default=0)),
                ('progress_card_pending_sections', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_wise_exam_result_status', to='branches.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_wise_exam_result_status', to='branches.branch')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_wise_exam_result_status', to='exams.exam')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_branch_exam_result_status', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_wise_exam_result_status', to='exams.examresultstatus')),
            ],
            options={
                'verbose_name': 'Branch Wise Exam Result Status',
                'verbose_name_plural': 'Branch Wise Exams Result Status',
                'indexes': [models.Index(fields=['academic_year'], name='exams_branc_academi_af3fcf_idx'), models.Index(fields=['branch'], name='exams_branc_branch__937d85_idx'), models.Index(fields=['exam'], name='exams_branc_exam_id_73b07b_idx'), models.Index(fields=['status'], name='exams_branc_status__5a9508_idx'), models.Index(fields=['is_visible'], name='exams_branc_is_visi_bbd80f_idx'), models.Index(fields=['marks_entry_expiry_datetime'], name='exams_branc_marks_e_56dfe3_idx'), models.Index(fields=['is_active'], name='exams_branc_is_acti_a63f4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'branch', 'exam'), name='unique_branch_wise_exam_result_status')],
            },
        ),
        migrations.CreateModel(
            name='SectionWiseExamResultStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('marks_completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('marks_entry_expiry_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_progress_card_downloaded', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_exam_result_status', to='branches.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_exam_result_status', to='branches.branch')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_exam_result_status', to='exams.exam')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_section_exam_result_status', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_exam_result_status', to='students.section')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_exam_result_status', to='exams.examresultstatus')),
            ],
            options={
                'verbose_name': 'Section Exam Results Status',
                'verbose_name_plural': 'Section Exams Result Status',
                'indexes': [models.Index(fields=['academic_year'], name='exams_secti_academi_537c63_idx'), models.Index(fields=['branch'], name='exams_secti_branch__f26405_idx'), models.Index(fields=['section'], name='exams_secti_section_50d5de_idx'), models.Index(fields=['exam'], name='exams_secti_exam_id_adc486_idx'), models.Index(fields=['status'], name='exams_secti_status__b281bc_idx'), models.Index(fields=['is_visible'], name='exams_secti_is_visi_99eb5a_idx'), models.Index(fields=['marks_entry_expiry_datetime'], name='exams_secti_marks_e_10934d_idx'), models.Index(fields=['is_active'], name='exams_secti_is_acti_9e87ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'branch', 'section', 'exam'), name='unique_section_wise_exam_result_status')],
                'unique_together': {('academic_year', 'branch', 'section', 'exam')},
            },
        ),
    ]
