# Generated by Django 5.2.6 on 2025-10-07 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_section'),
        ('exams', '0010_examresultstatus_exam_marks_entry_expiry_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchwiseexamresultstatus',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_wise_exam_result_status', to='branches.academicyear'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams_academic_year', to='branches.academicyear'),
        ),
        migrations.AlterField(
            model_name='sectionwiseexamresultstatus',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_exam_result_status', to='branches.academicyear'),
        ),
    ]
