# Generated by Django 5.2.6 on 2025-10-08 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_delete_section'),
        ('exams', '0012_remove_examresultstatus_code_alter_exam_name_and_more'),
        ('students', '0009_remove_section_number_of_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='branchwiseexamresultstatus',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_branch_exam_result_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams_academic_year', to='branches.academicyear'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams_exam_type', to='exams.examtype'),
        ),
        migrations.AlterField(
            model_name='examinstance',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_instance_exam', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examinstance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_instance_subject', to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results_attendance', to='exams.examattendancestatus'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results_exam_instance', to='exams.examinstance'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results_student', to='students.student'),
        ),
        migrations.AlterField(
            model_name='examskillresult',
            name='exam_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_results', to='exams.examresult'),
        ),
        migrations.AlterField(
            model_name='examskillresult',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_results', to='exams.subjectskill'),
        ),
        migrations.AlterField(
            model_name='examsubjectskillinstance',
            name='exam_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subject_skills_instance_exam_instance', to='exams.examinstance'),
        ),
        migrations.AlterField(
            model_name='examsubjectskillinstance',
            name='subject_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subject_skill_instance_subject_skill', to='exams.subjectskill'),
        ),
        migrations.AlterField(
            model_name='gradeboundary',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_bound_exam_type', to='exams.examtype'),
        ),
        migrations.AlterField(
            model_name='gradeboundary',
            name='orientation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_bound_orientation', to='students.orientation'),
        ),
        migrations.AlterField(
            model_name='sectionwiseexamresultstatus',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_section_exam_result_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentexamsummary',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_summary_exam', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='studentexamsummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_summary_student', to='students.student'),
        ),
        migrations.AlterField(
            model_name='subjectskill',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.examstatus'),
        ),
    ]
