# Generated by Django 5.2.6 on 2025-10-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_examstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchwiseexamresultstatus',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_wise_exam_result_status', to='exams.examresultstatus'),
        ),
        migrations.AlterField(
            model_name='sectionwiseexamresultstatus',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_exam_result_status', to='exams.examresultstatus'),
        ),
    ]
