# Generated by Django 5.2.6 on 2025-10-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_alter_branchwiseexamresultstatus_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
