# Generated by Django 5.2.6 on 2025-10-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_exam_is_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='exam_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_results_attendance', to='exams.examattendancestatus'),
        ),
    ]
