# Generated by Django 5.2.6 on 2025-10-11 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_rename_examp_skill_result_id_examskillresult_exam_skill_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examskillresult',
            name='exam_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_skill_results_attendance', to='exams.examattendancestatus'),
        ),
    ]
