# Generated by Django 5.2.6 on 2025-10-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_examskillresult_exam_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradeboundary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gradeboundary',
            name='grade',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='gradeboundary',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='gradeboundary',
            name='orientation',
        ),
    ]
