# Generated by Django 5.2.6 on 2025-10-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_alter_gradeboundary_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeboundary',
            options={'ordering': ['-min_percentage'], 'verbose_name_plural': 'Grade Boundaries'},
        ),
        migrations.AddField(
            model_name='examresult',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results_grade', to='exams.gradeboundary'),
        ),
        migrations.AddIndex(
            model_name='gradeboundary',
            index=models.Index(fields=['min_percentage', 'max_percentage'], name='exams_grade_min_per_cf40e0_idx'),
        ),
    ]
