# Generated by Django 5.2.6 on 2025-09-24 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('must_change_password', models.BooleanField(default=True)),
                ('academic_devisions', models.ManyToManyField(blank=True, related_name='user_academic_division', to='branches.academicdevision')),
                ('branches', models.ManyToManyField(blank=True, related_name='user_locations', to='branches.branch')),
                ('states', models.ManyToManyField(blank=True, related_name='user_states', to='branches.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('zones', models.ManyToManyField(blank=True, related_name='user_zones', to='branches.zone')),
            ],
        ),
    ]
