# Generated by Django 5.2.6 on 2025-09-25 06:26

import usermgmt.fields
import usermgmt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='user_classes', to='students.classname'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orientations',
            field=models.ManyToManyField(blank=True, related_name='user_orientations', to='students.orientation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=usermgmt.fields.WEBPField(blank=True, null=True, upload_to=usermgmt.models.user_profile_images),
        ),
    ]
