# Generated by Django 5.2.6 on 2025-10-29 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usermgmt', '0002_userprofile_classes_userprofile_orientations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='varna_profile_short_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='varna_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='varna_user_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VarnaProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('varna_profile_short_code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='varna_profiles_groups', to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Varna Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='varna_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles_varna_profile', to='usermgmt.varnaprofiles'),
        ),
    ]
