# Generated by Django 5.2.6 on 2025-10-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_userprofile_varna_profile_short_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_varna_user_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
