# Generated by Django 5.2.6 on 2025-10-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0004_userprofile_is_varna_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='varnaprofiles',
            name='varna_profile_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
