# Generated by Django 5.2.6 on 2025-10-15 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0020_alter_gradeboundary_options_examresult_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamProgressCardTemplate',
            fields=[
                ('template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_template', models.TextField(blank=True, null=True)),
                ('css_styles', models.TextField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_card_temp_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_card_temp_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamProgressCardMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_card_mapping_created_by', to=settings.AUTH_USER_MODEL)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='progress_card_mapping', to='exams.exam')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_card_mapping_updated_by', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_mappings', to='progresscard.examprogresscardtemplate')),
            ],
            options={
                'verbose_name': 'Exam Progress Card Mapping',
                'verbose_name_plural': 'Exam Progress Card Mappings',
                'indexes': [models.Index(fields=['is_active'], name='progresscar_is_acti_1762e4_idx'), models.Index(fields=['exam'], name='progresscar_exam_id_945426_idx'), models.Index(fields=['template'], name='progresscar_templat_59a243_idx')],
            },
        ),
    ]
